// ============================================================
// DigiCraft Store - Product Data & Constants
// ============================================================

import { Product, Review, Testimonial, FAQ } from './types';

// ── Product Catalog ──────────────────────────────────────────
export const products: Product[] = [
  {
    id: 'prod-001',
    name: 'Ultimate Notion Life OS',
    slug: 'notion-life-os',
    shortDescription: 'All-in-one Notion dashboard to organize your entire life.',
    description: 'The Ultimate Notion Life OS is a comprehensive, beautifully designed system that combines task management, habit tracking, goal setting, finance tracking, and knowledge management in one powerful dashboard. Built for entrepreneurs and students who want to take control of their daily workflow without switching between multiple apps.',
    price: 799,
    originalPrice: 1499,
    currency: '₹',
    category: 'notion-templates',
    tags: ['productivity', 'notion', 'dashboard', 'life-management'],
    images: [
      'https://images.pexels.com/photos/5706032/pexels-photo-5706032.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
      'https://images.pexels.com/photos/5706035/pexels-photo-5706035.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
    ],
    rating: 4.9,
    reviewCount: 234,
    salesCount: 1250,
    featured: true,
    bestseller: true,
    newArrival: false,
    limitedOffer: true,
    stockLeft: 12,
    whatsIncluded: [
      '15+ linked databases',
      'Dashboard with auto-updating widgets',
      'Habit tracker with streak counter',
      'Finance tracker with monthly reports',
      'Goal planner with OKR framework',
      'Video tutorial walkthrough (45 min)',
      'Lifetime free updates',
    ],
    whoIsFor: [
      'Entrepreneurs managing multiple projects',
      'Students organizing academics & life',
      'Freelancers tracking clients & income',
      'Anyone wanting a single system for everything',
    ],
    howToUse: [
      'Click the download link after purchase',
      'Duplicate the template to your Notion workspace',
      'Watch the setup video (included)',
      'Customize colors, categories & databases to your needs',
      'Start adding your tasks, goals & habits!',
    ],
    fileFormat: 'Notion Template Link',
    fileSize: 'Cloud-based',
    instantDownload: true,
    active: true,
    createdAt: '2024-01-15',
  },
  {
    id: 'prod-002',
    name: 'Canva Social Media Kit Pro',
    slug: 'canva-social-media-kit',
    shortDescription: '200+ Instagram, TikTok & LinkedIn templates for content creators.',
    description: 'Stop spending hours designing social media posts. This professional Canva template kit includes 200+ fully customizable designs for Instagram posts, stories, reels covers, TikTok thumbnails, and LinkedIn carousels. Perfect for content creators and small businesses who want consistent, on-brand visuals.',
    price: 1299,
    originalPrice: 2499,
    currency: '₹',
    category: 'canva-templates',
    tags: ['canva', 'social-media', 'instagram', 'design'],
    images: [
      'https://images.pexels.com/photos/5706035/pexels-photo-5706035.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
      'https://images.pexels.com/photos/12883029/pexels-photo-12883029.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
    ],
    rating: 4.8,
    reviewCount: 189,
    salesCount: 980,
    featured: true,
    bestseller: true,
    newArrival: false,
    limitedOffer: false,
    whatsIncluded: [
      '200+ editable Canva templates',
      '50 Instagram post templates',
      '40 Instagram story templates',
      '30 Reel cover templates',
      '30 TikTok thumbnail templates',
      '25 LinkedIn carousel templates',
      '25 Quote & tip templates',
      'Brand style guide template',
      'Color palette suggestions',
    ],
    whoIsFor: [
      'Content creators building their brand',
      'Small business owners doing DIY marketing',
      'Social media managers handling multiple clients',
      'Coaches & consultants growing online presence',
    ],
    howToUse: [
      'Access your Canva template links after purchase',
      'Open in Canva (free account works!)',
      'Replace text, images & colors with your brand',
      'Download and post to your social channels',
    ],
    fileFormat: 'Canva Template Links',
    fileSize: 'Cloud-based',
    instantDownload: true,
    active: true,
    createdAt: '2024-02-10',
  },
  {
    id: 'prod-003',
    name: 'ChatGPT Prompt Engineering Bible',
    slug: 'chatgpt-prompt-bible',
    shortDescription: '500+ proven AI prompts for business, marketing & creativity.',
    description: 'Master ChatGPT with 500+ battle-tested prompts organized by category. From writing killer marketing copy to generating code, creating business strategies, and producing creative content — this prompt library will 10x your AI productivity. Includes advanced techniques like chain-of-thought prompting and role-based prompts.',
    price: 499,
    originalPrice: 999,
    currency: '₹',
    category: 'ai-prompts',
    tags: ['chatgpt', 'ai', 'prompts', 'productivity'],
    images: [
      'https://images.pexels.com/photos/8533601/pexels-photo-8533601.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
      'https://images.pexels.com/photos/5706032/pexels-photo-5706032.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
    ],
    rating: 4.7,
    reviewCount: 412,
    salesCount: 2100,
    featured: true,
    bestseller: true,
    newArrival: false,
    limitedOffer: true,
    stockLeft: 5,
    whatsIncluded: [
      '500+ copy-paste prompts',
      '12 categories (marketing, coding, writing, etc.)',
      'Advanced prompting techniques guide',
      'Prompt formula templates',
      'Regular updates with new prompts',
      'Community access (Discord)',
      'Bonus: Midjourney prompt pack (50 prompts)',
    ],
    whoIsFor: [
      'Marketers wanting AI-powered content',
      'Entrepreneurs automating workflows',
      'Writers overcoming creative blocks',
      'Developers using AI for coding help',
    ],
    howToUse: [
      'Download the organized PDF/Notion template',
      'Browse prompts by category',
      'Copy any prompt and paste into ChatGPT',
      'Customize the [brackets] with your specific details',
      'Get amazing AI-generated outputs instantly!',
    ],
    fileFormat: 'PDF + Notion Template',
    fileSize: '15 MB',
    instantDownload: true,
    active: true,
    createdAt: '2024-03-01',
  },
  {
    id: 'prod-004',
    name: 'Digital Marketing Mastery Course',
    slug: 'digital-marketing-course',
    shortDescription: 'Complete course: SEO, ads, social media & email marketing.',
    description: 'Learn everything about digital marketing in this comprehensive course bundle. Covering SEO fundamentals, Google & Meta ads, social media strategy, email marketing automation, and analytics — this is your complete roadmap to becoming a digital marketing pro. Includes real case studies and actionable templates.',
    price: 2999,
    originalPrice: 4999,
    currency: '₹',
    category: 'course-bundles',
    tags: ['course', 'marketing', 'seo', 'ads'],
    images: [
      'https://images.pexels.com/photos/12883029/pexels-photo-12883029.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
      'https://images.pexels.com/photos/8533601/pexels-photo-8533601.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
    ],
    rating: 4.9,
    reviewCount: 156,
    salesCount: 650,
    featured: true,
    bestseller: false,
    newArrival: true,
    limitedOffer: true,
    stockLeft: 3,
    whatsIncluded: [
      '8+ hours of video content',
      '50+ downloadable templates & checklists',
      'SEO keyword research toolkit',
      'Ad copy swipe file (100+ examples)',
      'Email sequence templates',
      'Analytics dashboard template',
      'Certificate of completion',
      'Lifetime access + updates',
    ],
    whoIsFor: [
      'Aspiring digital marketers',
      'Small business owners doing own marketing',
      'Career switchers entering marketing',
      'Freelancers adding marketing to services',
    ],
    howToUse: [
      'Access the course portal via email link',
      'Follow modules in order (recommended)',
      'Complete assignments after each module',
      'Use included templates for your projects',
      'Join the community for Q&A support',
    ],
    fileFormat: 'Video Course + PDF + Templates',
    fileSize: '4.2 GB',
    instantDownload: true,
    active: true,
    createdAt: '2024-04-20',
  },
  {
    id: 'prod-005',
    name: 'UI/UX Design System Bundle',
    slug: 'ui-ux-design-system',
    shortDescription: 'Complete Figma design system with 1000+ components & icons.',
    description: 'Save hundreds of hours with this comprehensive Figma design system. Includes 1000+ carefully crafted UI components, 500+ icons, color systems, typography scales, and complete page templates for web and mobile apps. Built following atomic design principles with auto-layout and variants.',
    price: 1999,
    originalPrice: 3999,
    currency: '₹',
    category: 'design-assets',
    tags: ['figma', 'ui', 'ux', 'design-system'],
    images: [
      'https://images.pexels.com/photos/5706032/pexels-photo-5706032.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
      'https://images.pexels.com/photos/5706035/pexels-photo-5706035.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
    ],
    rating: 4.8,
    reviewCount: 98,
    salesCount: 420,
    featured: true,
    bestseller: false,
    newArrival: true,
    limitedOffer: false,
    whatsIncluded: [
      '1000+ UI components',
      '500+ custom icons (SVG)',
      '8 color themes (light & dark)',
      'Typography system (5 scales)',
      '20+ complete page templates',
      'Mobile app UI kit',
      'Dashboard template',
      'Auto-layout & variants setup',
      'Documentation & usage guide',
    ],
    whoIsFor: [
      'UI/UX designers building products',
      'Startup founders creating MVPs',
      'Frontend developers needing design specs',
      'Design teams wanting consistency',
    ],
    howToUse: [
      'Open the Figma file from your download link',
      'Duplicate to your Figma workspace',
      'Browse component library',
      'Drag & drop components into your designs',
      'Customize colors & typography using style guides',
    ],
    fileFormat: 'Figma File + SVG Icons',
    fileSize: '280 MB',
    instantDownload: true,
    active: true,
    createdAt: '2024-05-01',
  },
  {
    id: 'prod-006',
    name: 'Notion Finance Tracker',
    slug: 'notion-finance-tracker',
    shortDescription: 'Track income, expenses & investments with beautiful dashboards.',
    description: 'Take control of your money with this beautifully designed Notion finance tracker. Features automated calculations, visual charts, budget categories, investment portfolio tracking, and monthly/yearly reports. Simple enough for beginners, powerful enough for financial enthusiasts.',
    price: 299,
    originalPrice: 599,
    currency: '₹',
    category: 'notion-templates',
    tags: ['notion', 'finance', 'budget', 'tracker'],
    images: [
      'https://images.pexels.com/photos/8533601/pexels-photo-8533601.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
      'https://images.pexels.com/photos/12883029/pexels-photo-12883029.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
    ],
    rating: 4.6,
    reviewCount: 345,
    salesCount: 1800,
    featured: false,
    bestseller: true,
    newArrival: false,
    limitedOffer: false,
    whatsIncluded: [
      'Income & expense tracker',
      'Budget planner with categories',
      'Investment portfolio dashboard',
      'Monthly & yearly reports',
      'Bill payment reminders',
      'Savings goals tracker',
      'Setup video tutorial (20 min)',
    ],
    whoIsFor: [
      'Young professionals managing first salary',
      'Freelancers tracking irregular income',
      'Students budgeting wisely',
      'Anyone wanting clarity on spending',
    ],
    howToUse: [
      'Duplicate the Notion template',
      'Watch the quick setup video',
      'Add your income sources & categories',
      'Log expenses daily (takes 2 minutes)',
      'Review your dashboards weekly',
    ],
    fileFormat: 'Notion Template Link',
    fileSize: 'Cloud-based',
    instantDownload: true,
    active: true,
    createdAt: '2024-01-28',
  },
  {
    id: 'prod-007',
    name: 'Canva Brand Identity Kit',
    slug: 'canva-brand-kit',
    shortDescription: 'Logo, business cards, letterhead & presentation templates.',
    description: 'Build a professional brand identity without hiring a designer. This complete Canva kit includes logo templates, business card designs, letterhead, invoice templates, email signatures, and pitch deck presentations. Everything you need to look professional from day one.',
    price: 899,
    originalPrice: 1799,
    currency: '₹',
    category: 'canva-templates',
    tags: ['canva', 'branding', 'logo', 'business'],
    images: [
      'https://images.pexels.com/photos/5706035/pexels-photo-5706035.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
      'https://images.pexels.com/photos/5706032/pexels-photo-5706032.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
    ],
    rating: 4.7,
    reviewCount: 167,
    salesCount: 720,
    featured: true,
    bestseller: false,
    newArrival: false,
    limitedOffer: false,
    whatsIncluded: [
      '30+ logo template variations',
      '10 business card designs',
      '5 letterhead templates',
      '5 invoice templates',
      '3 email signature designs',
      '2 pitch deck templates (20+ slides each)',
      'Brand guidelines template',
      'Color & font pairing guide',
    ],
    whoIsFor: [
      'New business owners establishing brand',
      'Freelancers needing professional materials',
      'Startups with limited design budget',
      'Side hustlers building credibility',
    ],
    howToUse: [
      'Access all Canva templates via links',
      'Choose your favorite designs',
      'Replace placeholder text & images',
      'Apply your brand colors (guide included)',
      'Download in any format (PDF, PNG, etc.)',
    ],
    fileFormat: 'Canva Template Links',
    fileSize: 'Cloud-based',
    instantDownload: true,
    active: true,
    createdAt: '2024-02-20',
  },
  {
    id: 'prod-008',
    name: 'Complete AI Automation Toolkit',
    slug: 'ai-automation-toolkit',
    shortDescription: 'Zapier + Make.com workflows, AI prompts & automation guides.',
    description: 'Automate your entire business with this toolkit. Includes pre-built Zapier and Make.com workflows, AI integration guides, prompt libraries for content creation, and step-by-step tutorials for setting up automated email sequences, social media posting, and customer support bots.',
    price: 1499,
    originalPrice: 2999,
    currency: '₹',
    category: 'ai-prompts',
    tags: ['automation', 'ai', 'zapier', 'workflow'],
    images: [
      'https://images.pexels.com/photos/12883029/pexels-photo-12883029.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
      'https://images.pexels.com/photos/8533601/pexels-photo-8533601.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
    ],
    rating: 4.8,
    reviewCount: 89,
    salesCount: 380,
    featured: false,
    bestseller: false,
    newArrival: true,
    limitedOffer: true,
    stockLeft: 8,
    whatsIncluded: [
      '25 pre-built Zapier workflows',
      '15 Make.com scenarios',
      '200+ AI prompts for automation',
      'Email sequence templates (5 sequences)',
      'Social media auto-posting setup guide',
      'Customer support bot template',
      'Video tutorials (3+ hours)',
      'Community access',
    ],
    whoIsFor: [
      'Solopreneurs drowning in repetitive tasks',
      'Small teams wanting to scale without hiring',
      'Marketers automating campaigns',
      'Tech-curious people exploring AI tools',
    ],
    howToUse: [
      'Download the toolkit package',
      'Follow the setup guide for your platform',
      'Import pre-built workflows into Zapier/Make.com',
      'Customize triggers & actions for your business',
      'Watch videos for advanced configurations',
    ],
    fileFormat: 'PDF + JSON + Notion + Videos',
    fileSize: '1.8 GB',
    instantDownload: true,
    active: true,
    createdAt: '2024-05-10',
  },
];

// ── Reviews ──────────────────────────────────────────────────
export const reviews: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-001',
    userName: 'Priya Sharma',
    avatar: 'PS',
    rating: 5,
    comment: 'This Notion template completely changed how I manage my work and life. The setup video was super helpful. Worth every rupee!',
    date: '2024-03-15',
    verified: true,
  },
  {
    id: 'rev-2',
    productId: 'prod-001',
    userName: 'Rahul Mehta',
    avatar: 'RM',
    rating: 5,
    comment: 'As a freelancer juggling multiple clients, this was exactly what I needed. The finance tracker alone is worth the price.',
    date: '2024-04-02',
    verified: true,
  },
  {
    id: 'rev-3',
    productId: 'prod-002',
    userName: 'Ananya Gupta',
    avatar: 'AG',
    rating: 5,
    comment: 'My Instagram engagement went up 40% after using these templates. The designs are so professional and easy to customize in Canva!',
    date: '2024-03-28',
    verified: true,
  },
  {
    id: 'rev-4',
    productId: 'prod-003',
    userName: 'Vikram Singh',
    avatar: 'VS',
    rating: 4,
    comment: 'Great collection of prompts. Some are basic but the advanced prompting techniques section is gold. Already saved me hours of work.',
    date: '2024-04-10',
    verified: true,
  },
  {
    id: 'rev-5',
    productId: 'prod-004',
    userName: 'Sneha Patel',
    avatar: 'SP',
    rating: 5,
    comment: 'The most comprehensive digital marketing course I have taken. Real case studies and practical templates made all the difference.',
    date: '2024-05-01',
    verified: true,
  },
  {
    id: 'rev-6',
    productId: 'prod-005',
    userName: 'Arjun Nair',
    avatar: 'AN',
    rating: 5,
    comment: 'This design system is insanely well-organized. Saved our startup at least 2 months of design work. The icon set alone is worth it.',
    date: '2024-05-15',
    verified: true,
  },
];

// ── Testimonials ─────────────────────────────────────────────
export const testimonials: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Priya Sharma',
    role: 'Freelance Designer',
    avatar: 'https://images.pexels.com/photos/31395489/pexels-photo-31395489.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    comment: 'DigiCraft templates saved me 20+ hours every week. The quality is incredible and the support team is always responsive.',
    rating: 5,
  },
  {
    id: 'test-2',
    name: 'Rahul Mehta',
    role: 'Startup Founder',
    avatar: 'https://images.pexels.com/photos/8177853/pexels-photo-8177853.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    comment: 'Used the AI prompts toolkit and Notion Life OS for our team. Productivity jumped 3x. These are not just templates — they are systems.',
    rating: 5,
  },
  {
    id: 'test-3',
    name: 'Ananya Gupta',
    role: 'Content Creator, 50K followers',
    avatar: 'https://images.pexels.com/photos/13104099/pexels-photo-13104099.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    comment: 'The Canva templates are stunning! My brand looks so professional now. I get compliments on my posts every single day.',
    rating: 5,
  },
  {
    id: 'test-4',
    name: 'Vikram Singh',
    role: 'Digital Marketing Manager',
    avatar: 'https://images.pexels.com/photos/16764124/pexels-photo-16764124.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    comment: 'The marketing course bundle was comprehensive and practical. Applied the strategies and saw ROI within the first month.',
    rating: 5,
  },
];

// ── FAQs ─────────────────────────────────────────────────────
export const faqs: FAQ[] = [
  {
    question: 'How do I receive my digital products after purchase?',
    answer: 'Immediately after payment, you\'ll receive an email with download links. You can also access all your purchases from your dashboard. Most products are available as instant downloads or cloud-based template links.',
  },
  {
    question: 'Can I get a refund on digital products?',
    answer: 'Since digital products can be copied instantly, we generally don\'t offer refunds. However, if you experience technical issues preventing you from accessing the product, contact us within 7 days and we\'ll make it right.',
  },
  {
    question: 'Do I need a paid Canva/Notion account to use templates?',
    answer: 'Most of our templates work with free Canva and Notion accounts. Some advanced features may require Canva Pro, but we clearly mention this in the product description. Notion templates always work with free accounts.',
  },
  {
    question: 'Are updates included for free?',
    answer: 'Yes! All our products include lifetime free updates. When we add new templates, features, or improvements, you\'ll get them automatically or receive an email with the updated download link.',
  },
  {
    question: 'Can I use these templates for client work?',
    answer: 'Our standard license allows personal and commercial use for your own business. For using templates in client projects, you would need to purchase a separate copy for each client, or contact us for a multi-use license.',
  },
  {
    question: 'What payment methods do you accept?',
    answer: 'We accept all major credit/debit cards, UPI (Google Pay, PhonePe, Paytm), net banking, and popular wallets through Razorpay for Indian customers. International customers can pay via Stripe (cards, Apple Pay, Google Pay).',
  },
  {
    question: 'Do you offer bundle discounts?',
    answer: 'Yes! Buy any 3 products and get 20% off automatically at checkout. We also run seasonal sales with up to 50% off. Subscribe to our newsletter to get notified about exclusive deals.',
  },
];

// ── Category labels ──────────────────────────────────────────
export const categoryLabels: Record<string, string> = {
  'all': 'All Products',
  'notion-templates': 'Notion Templates',
  'canva-templates': 'Canva Templates',
  'ai-prompts': 'AI Prompt Libraries',
  'course-bundles': 'Course Bundles',
  'design-assets': 'Design Assets',
};

// ── Category icons (emoji) ───────────────────────────────────
export const categoryEmojis: Record<string, string> = {
  'notion-templates': '📝',
  'canva-templates': '🎨',
  'ai-prompts': '🤖',
  'course-bundles': '📚',
  'design-assets': '✨',
};
